[package]
name = "chessicles"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"
rand = "0.9.1"
rand_chacha = "0.9.0"

[profile.dev]
opt-level = 1

# Optimize packages for faster dev compiles times.
[profile.dev.package."*"]
opt-level = 3
